[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/awslabs/aws-lambda-go-api-proxy"
  branch = "master"
  
[[constraint]]
  name = "github.com/gorilla/context"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  branch = "master"
  