[[constraint]]
  name = "github.com/urfave/negroni"
  branch = "master"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/awslabs/aws-lambda-go-api-proxy"
  branch = "master"
  
[[constraint]]
  name = "github.com/gorilla/context"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/auth0/go-jwt-middleware"
  branch = "master"

