service: serverless-go

provider:
  name: aws
  runtime: go1.x
  environment:
    DATASTORE_URL: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}.DATASTORE_URL}  

functions:
  api:
    handler: bin/main
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

package:
  exclude:
    - ./**
  include:
    - ./bin/**

plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
      package:initialize: make compile
